cors:
  originPatterns: http://localhost:8080,http://localhost:3000
file:
  upload-dir: /github_projetos/java/code/uploadDir
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_management
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

#logging:
#  level:
#    com.management.product: DEBUG

spring-doc:
  paths-to-match: /products/**
  swagger-ui:
    use-root-path: true
