spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_management
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
